
name: generate v2ray subscribe url link

on:
  schedule:
    - cron: '* */2 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate_subscribe_url:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        yarn --frozen-lockfile
    - name: Run scripts
      run: |
        node index.js
      env:
        GH_USERNAME: ${{secrets.GH_USERNAME}}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        SUBSCRIBE_GIST_ID: ${{secrets.SUBSCRIBE_GIST_ID}}
        VMESS_GIST_ID: ${{secrets.VMESS_GIST_ID}}
        PASSWORD: ${{secrets.PASSWORD}}